### PR TITLE
Setup car model/TF for use in RVIZ

### PR DESCRIPTION
**Pull request by frk2**
- Add a car model since it looks cool. Add camera and radar TFs

For help in visualizing radar tracks
to test:

1. Launch rviz2
2. launch src/launch/all_launch.py

### CODE REVIEW

**Comment by J-Rojas** [comment]
There's no file src/launch/all_launch.launch in the repo. Did you forget to add it?

**Comment by J-Rojas** [comment]
BTW, this new LaunchDescription is bleeding edge (just added to ROS2 last week). It requires use of compiling ROS2 from the master branch until Bouncy is released. We should update the docs to make that clear.

**Comment by frk2** [comment]
https://github.com/frk2/opencaret/blob/faraz/rviz_car_model/src/launch/all_launch.py ?

**Comment by frk2** [comment]
Yeah totally bleeding edge. This stuff is gonna be part of the next stable release so makes sense to switch to it now.

**Comment by J-Rojas** [comment]
I've upgraded to 18.04, built ROS2 from source. I'm unable to use 'launch src/launch/all_launch.py'
However I can use `ros2 launch src/launch/all_launch.py`.
I don't see any meshes in rviz2. What should I do to see the car model?

**Comment by J-Rojas** [comment]
There's a hard-coded path the the mesh in the default.rviz file. This will have to be solved at the some point. Merging since this doesn't affect operation.

**Pull request merged**
